### PR TITLE
Initial DNS Support

### PR DESCRIPTION
**Pull request by mmellison**
Added initial DNS support, currently supporting clients running resolvconf / openresolv.

(Reference pritunl/pritunl#191)

[Review on Reviewable](https://reviewable.io/reviews/pritunl/pritunl-client/12)

### CODE REVIEW

**Comment by InAnimaTe** [comment]
Just tested this and works perfectly!!! Thanks soo much seglberg!

**Comment by zachhuff386** [comment]
Added in v1.0.810.68, the IntelliJ Idea directory can be excluded using a global gitignore

**Comment by satiani** [comment]
How do I build the client on OS X to take advantage of the DNS facility?

**Comment by zachhuff386** [comment]
This client is only for linux

**Pull request merged**
